export const ADD_CASH = "ADD_CASH"
export const GET_CASH = "GET_CASH"

export const ADD_CUSTOMERS = "ADD_CUSTOMERS"
export const GET_CUSTOMERS = "GET_CUSTOMERS"
export const REMOVE_CUSTOMERS = "REMOVE_CUSTOMERS"
export const REMOVE_ALL_CUSTOMERS = "REMOVE_ALL_CUSTOMERS"
export const ADD_MANY_CUSTOMERS = "ADD_MANY_CUSTOMERS"